import "./globals.css";
import { Inter } from "next/font/google";
import { TodosContextProvider } from "./contexts/TodosContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TodosContextProvider>{children}</TodosContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
